version: '3.4'

networks:
  dev:
    driver: bridge

services:
  passwordservice:
    image: docker.io/library/passwordservice
    depends_on:
      - "passwordserver"
    container_name: passwordservice_container
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings_DefaultConnection=User Id=postgres;Password=postgres;Port=5432;Database=Passwords;Server=passwordserver;IntegratedSecurity=true;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  passwordserver:
    image: postgres:latest
    container_name: passwordserver
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=Passwords
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/volumes/
    networks:
      - dev

volumes:
  app_data: